#!/usr/bin/env python
"""
Find files with keywords in filename.

Author: Jyotirmoy Bhattacharya (jyotirmoy@jyotirmoy.net)
License: GPL
"""

USAGE = "jffind <directory> <keyword> ..."

import os
import os.path
import re
import sys
import icu
from collections import defaultdict

# Only files with the following extensions will
# be shown. Please note the leading period.
EXT_WHITELIST = set([".pdf",".djvu",".djv"])

g_transliterator = icu.Transliterator.createInstance(
    "NFD; [:Mn:] Remove; NFC; Lower", #no accents; lowercase
    icu.UTransDirection.FORWARD)

def normalize(s):
       return g_transliterator.transliterate(s)

def tokenize(s):
    toks = [x for x in re.split(r'\W|_',s) if x!='']
    return toks

def ngrams(seq,n):
    l = list(seq)
    N = len(l)
    if N<n:
        return
    for i in range(0,N-n+1):
        yield tuple(l[i:i+n])

def gen_path_tokens(top):
    for dirpath,dirnames,filenames in os.walk(top):
        for f in filenames:
            p = os.path.join(dirpath,f)
            base,ext = os.path.splitext(f)
            if ext.lower() not in EXT_WHITELIST:
                continue
            toks_l = tokenize(base)
            toks_l = [normalize(t) for t in toks_l]
            toks = set(toks_l)
            toks |= set(ngrams(toks_l,2))
            yield (p,toks)

def build_index(root):
    d = defaultdict(set)
    for name,toks in gen_path_tokens(root):
        for t in toks:
            d[t].add(name)
    return d

def find(idx,terms):
    terms = [normalize(t) for t in terms]
    if len(terms)==0:
        raise ValueError("Empty list of terms in find")
    termset = set(terms)
    term_2grams = set(ngrams(terms,2))
    
    #Find items which match all terms
    first_term = termset.pop()
    matches = idx.get(first_term,set())
    for t in termset:
        if not matches:
            break
        matches &= idx.get(t,set())

    #Ranking based on two-gram occurence
    def rank(c):
        return sum(1 for t in term_2grams
                     if c in idx.get(t,set()))

    return sorted(matches, key = rank, reverse = True)

if __name__=="__main__":
    if (len(sys.argv)<3):
        sys.stderr.write("Usage: "+USAGE+'\n')
        sys.exit(1)

    root = sys.argv[1]
    if not os.path.isdir(root):
        sys.stderr.write("Not a directory: {0}\n".format(root))
        sys.exit(2)

    idx = build_index(root)
    ans = find(idx,sys.argv[2:])
    for c in ans:
        print(c)
    

